language: php

php:
  - 7.2

services:
  - docker

stages:
- name: check
- name: deploy
  if: branch = master

jobs:
  include:
    - stage: check
      script: echo test
    - stage: deploy
      script:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - $(aws ecr get-login --no-include-email --region eu-west-1)
        - ./deploy/deploy.sh
