version: "3.7"

services:
  nginx:
    image: phpstan-playground-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8082:80
    links:
      - fpm
    volumes:
      - source-code:/usr/deploy:ro

  fpm:
    image: phpstan-playground-fpm
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      target: development
    volumes:
      - source-code:/usr/deploy
    env_file: .env
    command: ["php-fpm"]

volumes:
  source-code:
    driver_opts:
      type: none
      device: $PWD
      o: bind
