version: "3.7"

services:
  nginx:
    image: phpstan-playground-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8082:80
    links:
      - fpm
      - fpm_xdebug
    volumes:
      - source-code:/usr/deploy:ro

  fpm:
    image: phpstan-playground-fpm-dev
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      target: development
    volumes:
      - source-code:/usr/deploy
    env_file: .env
    command: ["php-fpm"]

  fpm_xdebug:
    image: phpstan-playground-fpm-dev-xdebug
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      target: development-xdebug
    volumes:
      - source-code:/usr/deploy
    env_file: .env
    environment:
      PHP_IDE_CONFIG: "serverName=Xdebug"
    command: ["php-fpm"]

volumes:
  source-code:
    driver_opts:
      type: none
      device: $PWD
      o: bind
