version: "2.3"

services:
  nginx:
    image: phpstan-playground-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8082:80
    links:
      - fpm
    volumes_from:
      - fpm:ro

  fpm:
    image: phpstan-playground-fpm
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      target: development
    volumes:
      - ./:/usr/deploy
    env_file: .env
    command: ["php-fpm"]
